language: c
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq flex bison
before_script:
   - sudo add-apt-repository ppa:dns/gnu -y
   - sudo apt-get update -q
   - sudo apt-get install --only-upgrade autoconf
script: automake --add-missing && autoreconf && ./configure && make && make check
compiler:
   - gcc
   - clang
