language: c
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq flex bison
script: autoconf && automake --add-missing && ./configure && make && make check
compiler:
   - gcc
   - clang
